# Generated by Django 3.2.7 on 2021-10-21 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_price', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=255, verbose_name='Наименование продукта')),
                ('composition', models.CharField(max_length=1027, verbose_name='Состав')),
                ('amount', models.PositiveIntegerField(default=0, null=True, verbose_name='Количество продукта в наличае')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена продукта')),
                ('inStock', models.BooleanField(default=True, verbose_name='В наличае')),
                ('articul', models.CharField(max_length=127, verbose_name='Артикул')),
                ('raiting_general', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, null=True, verbose_name='Рейтинг продукта')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='Категория продукта')),
            ],
        ),
        migrations.CreateModel(
            name='RaitingStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Raiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appraiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Оценщик')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raitings', to='products.products', verbose_name='Продукт')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raitings', to='products.raitingstar', verbose_name='Количество звезд')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_prod', models.CharField(max_length=2047)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('adress', models.CharField(max_length=255, verbose_name='Адрес')),
                ('status', models.CharField(choices=[('Успешно доставлен', 'Succsess'), ('В ожидании доставки', 'In Pending'), ('Отменён', 'Canceled')], default='В ожидании доставки', max_length=50)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.cart', verbose_name='Корзина')),
            ],
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_product', models.PositiveIntegerField(default=0)),
                ('general_price', models.PositiveIntegerField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_product',
            field=models.ManyToManyField(related_name='products', through='products.CartProduct', to='products.Products'),
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
