# Generated by Django 3.2.7 on 2021-09-25 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(default='', max_length=255, verbose_name='Наименование продукта')),
                ('composition', models.CharField(default='', max_length=1027, verbose_name='Состав')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена продукта')),
                ('inStock', models.BooleanField(default=True, verbose_name='В наличае')),
                ('articul', models.CharField(default='', max_length=127, verbose_name='Артикул')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='Категория продукта')),
            ],
        ),
    ]
