# Generated by Django 3.2.7 on 2021-10-12 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='customer',
        ),
    ]
