# Generated by Django 3.2.7 on 2021-09-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='articul',
            field=models.CharField(max_length=127, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='products',
            name='composition',
            field=models.CharField(max_length=1027, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name_product',
            field=models.CharField(max_length=255, verbose_name='Наименование продукта'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена продукта'),
        ),
    ]
