# Generated by Django 3.2.7 on 2021-10-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_cart_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='amount',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Количество продукта в наличае'),
        ),
    ]
