# Generated by Django 3.2.7 on 2021-10-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_products_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_product',
            field=models.ManyToManyField(related_name='products', through='products.CartProduct', to='products.Products'),
        ),
    ]
